


INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1001, 'Akash', 'LEARN AWD_akdfajakfadasdfaf', CURRENT_DATE(), TRUE);



INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1002, 'Akash', 'LEARN AWD_akdfajakfadfadsfadf fdasfadsf', CURRENT_DATE(), TRUE);

